-- Database creation script for Business Details Extractor
-- Create this database in phpMyAdmin before running the tool

CREATE DATABASE IF NOT EXISTS `business_leads`;
USE `business_leads`;

-- Table structure for businesses
-- This table is designed to store all fields extracted by the tool
CREATE TABLE IF NOT EXISTS `businesses` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `address` TEXT,
  `phone` VARCHAR(255),
  `website` VARCHAR(255),
  `google_maps` TEXT,
  `facebook` VARCHAR(255),
  `instagram` VARCHAR(255),
  `digital_gaps` TEXT,
  `rating` VARCHAR(50),
  `hours` TEXT,
  `email` VARCHAR(255),
  `whatsapp` VARCHAR(255),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for generated_prompts
-- Stores history of prompts generated by the tool
CREATE TABLE IF NOT EXISTS `generated_prompts` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `business_type` VARCHAR(255),
  `location` VARCHAR(255),
  `prompt_text` LONGTEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------
-- UPDATE DB: v1.3 Lead Tracking & Batch Management
-- Timestamp: 2026-05-14 10:30:00 IST
-- ------------------------------------------------------

ALTER TABLE `businesses` 
ADD COLUMN IF NOT EXISTS `business_type` VARCHAR(100) AFTER `whatsapp`,
ADD COLUMN IF NOT EXISTS `batch_id` VARCHAR(100) AFTER `business_type`,
ADD COLUMN IF NOT EXISTS `is_closed` TINYINT(1) DEFAULT 0 AFTER `batch_id`,
ADD COLUMN IF NOT EXISTS `is_review_later` TINYINT(1) DEFAULT 0 AFTER `is_closed`;
 
-- ------------------------------------------------------
-- UPDATE DB: v1.4 Restore State Field
-- Timestamp: 2026-05-14 11:45:00 IST
-- ------------------------------------------------------

ALTER TABLE `businesses` 
ADD COLUMN IF NOT EXISTS `state` VARCHAR(100) AFTER `address`;
